//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webmvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BIENTHE
    {
        public string MaBT { get; set; }
        public string MaSP { get; set; }
        public string Mau { get; set; }
        public string Size { get; set; }
        public Nullable<int> TonKho { get; set; }
    
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
