//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webmvc.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DO_AN_GIOVANNIEntities : DbContext
    {
        public DO_AN_GIOVANNIEntities()
            : base("name=DO_AN_GIOVANNIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BIENTHE> BIENTHEs { get; set; }
        public DbSet<DANHMUC> DANHMUCs { get; set; }
        public DbSet<DONHANG> DONHANGs { get; set; }
        public DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public DbSet<THUONGHIEU> THUONGHIEUx { get; set; }
        public DbSet<SANPHAM> SANPHAMs { get; set; }
    }
}
