//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webmvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        public SANPHAM()
        {
            this.BIENTHEs = new HashSet<BIENTHE>();
            this.DONHANGs = new HashSet<DONHANG>();
        }
    
        public string MaSP { get; set; }
        public string TenSP { get; set; }
        public Nullable<decimal> GiaGoc { get; set; }
        public Nullable<decimal> GiaGiam { get; set; }
        public string MaTH { get; set; }
        public string MaDM { get; set; }
        public string MoTa { get; set; }
        public string AnhBia { get; set; }
    
        public virtual ICollection<BIENTHE> BIENTHEs { get; set; }
        public virtual DANHMUC DANHMUC { get; set; }
        public virtual ICollection<DONHANG> DONHANGs { get; set; }
        public virtual THUONGHIEU THUONGHIEU { get; set; }
    }
}
