//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webmvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THUONGHIEU
    {
        public THUONGHIEU()
        {
            this.SANPHAMs = new HashSet<SANPHAM>();
        }
    
        public string MaTH { get; set; }
        public string TenTH { get; set; }
        public string MoTa { get; set; }
    
        public virtual ICollection<SANPHAM> SANPHAMs { get; set; }
    }
}
